version: "3"
services:
  wenv:
    image: my-virtual-robot-23:2.0
    network_mode: "host"
    #image: virtualrobotdisi23:1.0
    #image: docker.io/natbodocker/virtualrobotdisi:4.0
    #image: virtualrobotdisi:4.0
    #ports:
    #  - 8090:8090
    #  - 8091:8091/tcp
    #  - 8091:8091/udp
  robot:
     image: basicrobot-dist:1.0
     network_mode: "host"
     #image: docker.io/natbodocker/basicrobot22:2.0
     #image: basicrobot22:1.0
     #ports:
     #  - 8020:8020/tcp
     #  - 8020:8020/udp
     depends_on:
       - wenv
  wasteservice:
     image: waste-service:1.0
     network_mode: "host"
     #ports:
     #  - 8025:8025
     depends_on:
       - robot 
## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f wasteService-system-dist.yaml up

