/* Generated by AN DISI Unibo */ 
package it.unibo.ctxledqak22
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.123", this, "wasteservice.pl", "sysRules.pl","ctxledqak22"
	)
}

