/* Generated by AN DISI Unibo */ 
package it.unibo.wasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var MAXPB = 500L;
				var MAXGB = 500L;
				var CurrentPB = 0L;
				var CurrentGB = 0L;
				var Trolley_Status = "IDLE"; 
				
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("the WasteService is waiting..")
					}
					 transition(edgeName="t02",targetState="handle_request",cond=whenRequest("waste_request"))
					transition(edgeName="t03",targetState="handle_led",cond=whenEvent("trolley_status"))
					transition(edgeName="t04",targetState="handle_led",cond=whenEvent("trolley_position"))
				}	 
				state("handle_request") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("waste_request(MATERIAL,TRUCKLOAD)"), Term.createTerm("waste_request(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var Material 	= payloadArg(0);
												var TruckLoad 	= payloadArg(1).toLong();
								println("WasteService | arrived request: $Material load with weight $TruckLoad")
								if(  Trolley_Status.equals("IDLE") || Trolley_Status.equals("MOVING") || Trolley_Status.equals("WORKING")  
								 ){if(  Material.equals("plastic")  
								 ){if(  TruckLoad + CurrentPB <= MAXPB  
								 ){answer("waste_request", "loadaccept", "loadaccept(plastic,$TruckLoad)"   )  
								 CurrentPB += TruckLoad  
								println("WasteService | current plastic weight: $CurrentPB")
								forward("execute", "execute(plastic,$TruckLoad)" ,"transporttrolley" ) 
								println("WasteService | send EXECUTE   to the Transport Trolley")
								}
								else
								 {answer("waste_request", "loadrejected", "loadrejected(plastic,$TruckLoad)"   )  
								 }
								}
								else
								 {if(  TruckLoad + CurrentGB <= MAXGB  
								  ){answer("waste_request", "loadaccept", "loadaccept(glass,$TruckLoad)"   )  
								  CurrentGB += TruckLoad  
								 println("WasteService | current glass weight: $CurrentGB")
								 forward("execute", "execute(glass,$TruckLoad)" ,"transporttrolley" ) 
								 println("WasteService | send EXECUTE   to the Transport Trolley")
								 }
								 else
								  {answer("waste_request", "loadrejected", "loadrejected(glass,$TruckLoad)"   )  
								  }
								 }
								emit("containers_weight", "containers_weight($CurrentGB,$CurrentPB)" ) 
								}
								else
								 {println("Richiesta messa in coda")
								 }
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("handle_led") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("trolley_status(TROLLEY_STATUS)"), Term.createTerm("trolley_status(TROLLEY_STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Trolley_Status = payloadArg(0)  
								if(  Trolley_Status.equals("WORKING")  
								 ){println("WasteService | Received new trolley_status: $Trolley_Status")
								 var Led_Status = "LED_BLINKS"  
								emit("change_led", "change_led($Led_Status)" ) 
								}
								if(  Trolley_Status.equals("STOPPED")  
								 ){println("WasteService | Received new trolley_status: $Trolley_Status")
								 var Led_Status = "LED_ON"  
								emit("change_led", "change_led($Led_Status)" ) 
								}
						}
						if( checkMsgContent( Term.createTerm("trolley_position(POSITION)"), Term.createTerm("trolley_position(TROLLEY_POSITION)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Trolley_Position = payloadArg(0)  
								if(  Trolley_Position.equals("HOME")  
								 ){println("WasteService | Received new trolley_position: $Trolley_Position")
								 var Led_Status = "LED_OFF"  
								emit("change_led", "change_led($Led_Status)" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
