/* Generated by AN DISI Unibo */ 
package it.unibo.wastetruck

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wastetruck ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Material 	= "";
				var TruckLoad 	= 0L;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("the WasteTruck is waiting..")
						delay(3000) 
						 val Load = kotlin.random.Random.nextLong(10,100)  
						request("waste_request", "waste_request(plastic,$Load)" ,"wasteservice" )  
					}
					 transition(edgeName="t00",targetState="accepted",cond=whenReply("loadaccept"))
					transition(edgeName="t01",targetState="rejected",cond=whenReply("loadrejected"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("loadaccept(MATERIAL,TRUCKLOAD)"), Term.createTerm("loadaccept(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Material 	= payloadArg(0);
												TruckLoad 	= payloadArg(1).toLong();
								println("WasteTruck | accepted $Material load with weight $TruckLoad")
						}
					}
				}	 
				state("rejected") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("loadrejected(MATERIAL,TRUCKLOAD)"), Term.createTerm("loadrejected(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Material 	= payloadArg(0);
												TruckLoad 	= payloadArg(1).toLong();
								println("WasteTruck | rejected $Material load with weight $TruckLoad")
						}
					}
				}	 
			}
		}
}
