/* Generated by AN DISI Unibo */ 
package it.unibo.wastetruckmock

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wastetruckmock ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var Material 	= "";
				var TruckLoad 	= 0L;
				var Materials = arrayListOf<String>("glass", "plastic");
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTETRUCK | starts.")
						delay(3000) 
						 
									val Load = kotlin.random.Random.nextLong(10,100) 
									val randomIndex = kotlin.random.Random.nextInt(Materials.size);
						   			val Mat = Materials[randomIndex]
						request("waste_request", "waste_request($Mat,$Load)" ,"wasteservice" )  
						println("WASTETRUCK | sent request of $Mat with load $Load.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="accepted",cond=whenReply("loadaccept"))
					transition(edgeName="t01",targetState="rejected",cond=whenReply("loadrejected"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("loadaccept(MATERIAL,TRUCKLOAD)"), Term.createTerm("loadaccept(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Material 	= payloadArg(0);
												TruckLoad 	= payloadArg(1).toLong();
								println("WASTETRUCK | accepted $Material with load $TruckLoad.")
								request("free_request", "free_request(arg)" ,"wasteservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="leave_Indoor",cond=whenReply("free_indoor"))
				}	 
				state("rejected") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("loadrejected(MATERIAL,TRUCKLOAD)"), Term.createTerm("loadrejected(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Material 	= payloadArg(0);
												TruckLoad 	= payloadArg(1).toLong();
								println("WASTETRUCK | rejected $Material load with weight $TruckLoad")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="leave_Indoor", cond=doswitch() )
				}	 
				state("leave_Indoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("WASTETRUCK | WasteTruck left Indoor area.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
