/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Status	= "IDLE";	
				var Position = "HOME";
				var Material = "";
				var PathHome = "";
				var PathIndoor = "";
				var PathContainer = "";
				
				var PathToDo = "";
				var LastState = ""; //to_indoor, to_container, to_home
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("the TransportTrolley is waiting..")
					}
					 transition(edgeName="t016",targetState="move_to_INDOOR",cond=whenRequest("pickup_request"))
					transition(edgeName="t017",targetState="trolley_stopped",cond=whenDispatch("stop_trolley"))
				}	 
				state("move_to_INDOOR") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("pickup_request(PATH_TO_INDOOR,MATERIAL)"), Term.createTerm("pickup_request(PATH_TO_INDOOR,MATERIAL)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
										 		PathIndoor = payloadArg(0)
										 		Material = payloadArg(1)
						}
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TRANSPORT TROLLEY | execute the path $PathIndoor to INDOOR.")
						request("dopath", "dopath($PathIndoor)" ,"pathexec" )  
						 Status = "WORKING"  
						 Position = "GENERIC"  
						emit("trolley_status", "trolley_status($Status)" ) 
						emit("trolley_position", "trolley_position($Position)" ) 
						 LastState = "to_indoor"  
					}
					 transition(edgeName="t118",targetState="pickup_action",cond=whenReply("dopathdone"))
					transition(edgeName="t119",targetState="pathfail",cond=whenReply("dopathfail"))
					transition(edgeName="t120",targetState="trolley_stopped",cond=whenDispatch("stop_trolley"))
				}	 
				state("pickup_action") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dopathdone(ARG)"), Term.createTerm("dopathdone(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(3000) 
								unibo.kotlin.planner22Util.updateMapWithPath( PathIndoor  )
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
								println("TRANSPORT TROLLEY | arrived to INDOOR.")
								 Position = "INDOOR"  
								emit("trolley_position", "trolley_position($Position)" ) 
								answer("pickup_request", "pickup_done", "pickup_done(DONE)"   )  
								println("TRANSPORT TROLLEY | pick up done.")
						}
					}
					 transition(edgeName="t221",targetState="move_to_Container",cond=whenRequest("storage_request"))
				}	 
				state("pathfail") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TRANSPORT TROLLEY| Error: Path fail!")
					}
				}	 
				state("move_to_Container") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("storage_request(PATH_TO_CONTAINER)"), Term.createTerm("storage_request(PATH_TO_CONTAINER)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
										 		PathContainer = payloadArg(0)
						}
						println("TRANSPORT TROLLEY | execute the path $PathContainer to $Material container ")
						 Status = "WORKING"  
						emit("led_status", "led_status(BLINKS)" ) 
						emit("trolley_status", "trolley_status($Status)" ) 
						request("dopath", "dopath($PathContainer)" ,"pathexec" )  
						 LastState = "to_container"  
					}
					 transition(edgeName="t322",targetState="settle_action",cond=whenReply("dopathdone"))
					transition(edgeName="t323",targetState="pathfail",cond=whenReply("dopathfail"))
					transition(edgeName="t324",targetState="trolley_stopped",cond=whenDispatch("stop_trolley"))
				}	 
				state("settle_action") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dopathdone(ARG)"), Term.createTerm("dopathdone(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(3000) 
								unibo.kotlin.planner22Util.updateMapWithPath( PathContainer  )
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
								println("TRANSPORT TROLLEY | arrived to $Material container")
								if(  Material.equals("plastic") 
								 ){ Position = "CONTAINERP"  
								}
								else
								 { Position = "CONTAINERG"  
								 }
						}
						emit("led_status", "led_status(BLINKS)" ) 
						emit("trolley_position", "trolley_position($Position)" ) 
						 Status = "IDLE"  
						emit("trolley_status", "trolley_status($Status)" ) 
						unibo.kotlin.planner22Util.showCurrentRobotState(  )
						delay(1500) 
						println("TRANSPORT TROLLEY | settled $Material on the Container.")
						answer("storage_request", "storage_done", "storage_done(DONE)"   )  
					}
					 transition(edgeName="t425",targetState="move_to_INDOOR",cond=whenRequest("pickup_request"))
					transition(edgeName="t426",targetState="move_to_HOME",cond=whenRequest("home_request"))
				}	 
				state("move_to_HOME") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TRANSPORT TROLLEY | coming back to HOME ")
						if( checkMsgContent( Term.createTerm("home_request(PATH_TO_HOME)"), Term.createTerm("home_request(PATH_TO_HOME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												PathHome = payloadArg(0)
								request("dopath", "dopath($PathHome)" ,"pathexec" )  
								delay(1500) 
						}
						 LastState = "to_home"  
					}
					 transition(edgeName="t527",targetState="back_to_home",cond=whenReply("dopathdone"))
					transition(edgeName="t528",targetState="pathfail",cond=whenReply("dopathfail"))
					transition(edgeName="t529",targetState="trolley_stopped",cond=whenDispatch("stop_trolley"))
				}	 
				state("back_to_home") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dopathdone(ARG)"), Term.createTerm("dopathdone(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("TRANSPORT TROLLEY | arrived HOME.")
								 Position = "HOME"  
								emit("led_status", "led_status(OFF)" ) 
								unibo.kotlin.planner22Util.showCurrentRobotState(  )
								emit("trolley_position", "trolley_position($Position)" ) 
								answer("home_request", "home_done", "home_done(DONE)"   )  
						}
					}
					 transition(edgeName="t630",targetState="move_to_INDOOR",cond=whenRequest("pickup_request"))
				}	 
				state("handle_stop") { //this:State
					action { //it:State
						println("WASTESERVICE | Trolley stopped by the sonar, wait for resume..")
						emit("trolley_status", "trolley_status(STOPPED)" ) 
						forward("stop_trolley", "stop_trolley(STOP)" ,"transporttrolley" ) 
					}
					 transition( edgeName="goto",targetState="savepath", cond=doswitch() )
				}	 
				state("savepath") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("dopathfail(ARG)"), Term.createTerm("dopathfail(PATH)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												PathToDo = payloadArg(0);
						}
						println("TRANSPORT TROLLEY | SAVE PATH: $PathToDo")
					}
					 transition( edgeName="goto",targetState="trolley_stopped", cond=doswitch() )
				}	 
				state("trolley_stopped") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TRANSPORT TROLLEY | STOPPED")
					}
					 transition(edgeName="t731",targetState="handle_resume",cond=whenDispatch("resume_trolley"))
				}	 
				state("handle_resume") { //this:State
					action { //it:State
						println("WASTESERVICE | resume trolley after sonar resume message.")
						emit("led_status", "led_status(BLINKS)" ) 
						emit("trolley_status", "trolley_status(WORKING)" ) 
						forward("resume_trolley", "resume_trolley(OK)" ,"transporttrolley" ) 
					}
					 transition( edgeName="goto",targetState="trolley_resumed", cond=doswitch() )
				}	 
				state("trolley_resumed") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("TRANSPORT TROLLEY | RESUME")
						if( checkMsgContent( Term.createTerm("resume_trolley(OK)"), Term.createTerm("resume_trolley(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												LastState = payloadArg(0)
						}
						println("TRASNSPORT TROLLEY | Last state of trolley: $LastState")
						request("dopath", "dopath($PathToDo)" ,"pathexec" )  
						 PathToDo = ""  
					}
					 transition(edgeName="t832",targetState="pickup_action",cond=whenReplyGuarded("dopathdone",{ LastState == "to_indoor"  
					}))
					transition(edgeName="t833",targetState="settle_action",cond=whenReplyGuarded("dopathdone",{ LastState == "to_container"  
					}))
					transition(edgeName="t834",targetState="back_to_home",cond=whenReplyGuarded("dopathdone",{ LastState == "to_home"  
					}))
					transition(edgeName="t835",targetState="pathfail",cond=whenReply("dopathfail"))
				}	 
			}
		}
}
