/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Status	= "IDLE";	
				var Position = "HOME";
				var Material = "";
				var TruckLoad = 0L;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("the transportTrolley is waiting..")
					}
					 transition(edgeName="t03",targetState="move_to_INDOOR",cond=whenDispatch("execute"))
				}	 
				state("move_to_INDOOR") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("execute(MATERIAL,TRUCKLOAD)"), Term.createTerm("execute(MATERIAL,TRUCKLOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
										 		Material = payloadArg(0)
										 		TruckLoad = payloadArg(1).toLong()
						}
						println("$name in ${currentState.stateName} | $currentMsg")
						println("transportTrolley | moving to INDOOR with $Material")
						 Status = "WORKING"  
						 Position = "GENERIC"  
						emit("trolley_status", "trolley_status(Status)" ) 
						emit("trolley_position", "trolley_position(Position)" ) 
						delay(500) 
						println("transportTrolley | arrived to INDOOR in status : $Status")
						println("transportTrolley | picking up $Material of load $TruckLoad")
						 Position = "INDOOR"  
						emit("trolley_position", "trolley_position(Position)" ) 
					}
					 transition( edgeName="goto",targetState="move_to_ContainerP", cond=doswitchGuarded({ Material.equals("plastic")  
					}) )
					transition( edgeName="goto",targetState="move_to_ContainerG", cond=doswitchGuarded({! ( Material.equals("plastic")  
					) }) )
				}	 
				state("move_to_ContainerP") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("transportTrolley | moving to plastic container ")
						 Status = "WORKING"  
						emit("trolley_status", "trolley_status(Status)" ) 
						delay(500) 
						println("transportTrolley | arrived to plastic container")
						 Position = "CONTAINERP"  
						emit("trolley_position", "trolley_position(Position)" ) 
						println("transportTrolley | settling plastic")
						delay(300) 
						 Status = "IDLE"  
						emit("trolley_status", "trolley_status(Status)" ) 
					}
					 transition( edgeName="goto",targetState="move_to_HOME", cond=doswitch() )
				}	 
				state("move_to_ContainerG") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("transportTrolley | moving to glass container ")
						 Status = "WORKING"  
						emit("trolley_status", "trolley_status(Status)" ) 
						delay(500) 
						println("transportTrolley | arrived to glass container")
						 Position = "CONTAINERG"  
						emit("trolley_position", "trolley_position(Position)" ) 
						println("transportTrolley | settling glass")
						delay(300) 
						 Status = "IDLE"  
						emit("trolley_status", "trolley_status(Status)" ) 
					}
					 transition( edgeName="goto",targetState="move_to_HOME", cond=doswitch() )
				}	 
				state("move_to_HOME") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("transportTrolley | coming back to HOME ")
						delay(500) 
						println("transportTrolley | arrived HOME")
						 Position = "HOME"  
						emit("trolley_position", "trolley_position(Position)" ) 
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
