/* Generated by AN DISI Unibo */ 
package it.unibo.ledqak22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Ledqak22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name STARTS")
					}
					 transition(edgeName="t00",targetState="handleThrill",cond=whenEvent("led_status"))
				}	 
				state("handleThrill") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led_status(STATUS)"), Term.createTerm("led_status(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Cmd = payloadArg(0)  
								if(  Cmd=="ON"  
								 ){ unibo.actor22comm.utils.ColorsOut.outappl( 
													"${name} - on", unibo.actor22comm.utils.ColorsOut.MAGENTA)
								println("LED | ON")
								}
								else
								 {if(  Cmd=="OFF"  
								  ){ unibo.actor22comm.utils.ColorsOut.outappl( 
								 						"${name} - off", unibo.actor22comm.utils.ColorsOut.GREEN)
								 println("LED | OFF")
								 }
								 else
								  {if(  Cmd=="BLINKS"  
								   ){ unibo.actor22comm.utils.ColorsOut.outappl( 
								  							"${name} - blinks", unibo.actor22comm.utils.ColorsOut.BLUE)
								  println("LED | BLINKS")
								  }
								  }
								 }
						}
					}
					 transition(edgeName="t01",targetState="handleThrill",cond=whenEvent("led_status"))
				}	 
			}
		}
}
